# Generated by Django 4.2.3 on 2026-01-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_auth", "0014_abstractuser_is_affiliate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateWithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bank_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("status", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_withdrawals",
                        to="custom_auth.user",
                    ),
                ),
            ],
            options={
                "db_table": "affiliate_withdraw_request",
            },
        ),
    ]
