# Generated by Django 4.2.11 on 2025-07-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='link',
            new_name='group_link',
        ),
    ]
