# Generated by Django 4.2.22 on 2025-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_link_group_group_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_scheduled',
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_patterns',
            field=models.IntegerField(default=1),
        ),
    ]
