# Generated by Django 4.2.22 on 2025-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_is_scheduled_group_number_of_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_link',
        ),
        migrations.AddField(
            model_name='group',
            name='group_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='group',
            name='group_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
