# Generated by Django 4.2.3 on 2025-10-24 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0004_remove_group_group_link_group_group_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupGroupSubscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.group",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        db_column="abstractuser_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
