# Generated by Django 4.2.3 on 2025-10-24 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0005_groupgroupsubscribers"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupWithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("0", "Accepted"),
                            ("1", "Pending"),
                            ("2", "Rejected"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("transaction_sms", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdraw_requests",
                        to="group.group",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_withdraw_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
