# Generated by Django 4.2.11 on 2025-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
