# Generated by Django 4.2.11 on 2025-01-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_user_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashier',
        ),
    ]
