# Generated by Django 4.2.11 on 2025-06-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_delete_cashier'),
        ('custom_auth', '0006_user_bonus_alter_abstractuser_telgram_id_and_more'),
    ]

    operations = [
    ]
