# Generated by Django 4.2.11 on 2025-06-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_merge_20250612_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractuser',
            old_name='telgram_id',
            new_name='telegram_id',
        ),
    ]
