# Generated by Django 4.2.3 on 2025-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0008_rename_telgram_id_abstractuser_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_withdraw_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="no_of_cash_deposited",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="no_of_games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="reserved_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="total_withdraw_amount_per_day",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38),
        ),
    ]
