# Generated by Django 4.2.3 on 2025-10-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_auth",
            "0009_user_last_withdraw_date_user_no_of_cash_deposited_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
