# Generated by Django 4.2.3 on 2025-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0010_user_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consecutive_losses",
            field=models.IntegerField(default=0),
        ),
    ]
