# Generated by Django 4.2.22 on 2025-10-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_user_consecutive_losses'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off_stake', models.JSONField(default=dict)),
                ('names', models.JSONField(default=list)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_players', models.IntegerField(default=0)),
            ],
        ),
    ]
