# Generated by Django 4.2.22 on 2025-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0012_randomplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomplayer',
            name='on_off_stake',
        ),
        migrations.AddField(
            model_name='randomplayer',
            name='on_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomplayer',
            name='stake',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
