# Generated by Django 4.2.3 on 2026-01-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_auth",
            "0013_remove_randomplayer_on_off_stake_randomplayer_on_off_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractuser",
            name="is_affiliate",
            field=models.BooleanField(default=False),
        ),
    ]
