# Generated by Django 4.2.3 on 2026-01-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0014_abstractuser_is_affiliate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliate_wallet",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
