# Generated by Django 5.1.1 on 2024-10-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.CharField(default='20', max_length=50)),
                ('numberofplayers', models.IntegerField(default=0)),
                ('playerCard', models.JSONField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('played', models.CharField(default='Created', max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('called_numbers', models.JSONField(default=[0])),
                ('random_numbers', models.JSONField(default=[0])),
                ('winner_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('admin_cut', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
