# Generated by Django 5.1.1 on 2024-10-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='numbers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='called_numbers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerCard',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='random_numbers',
            field=models.JSONField(default=dict),
        ),
    ]
