# Generated by Django 5.1.2 on 2024-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_card_numbers_alter_game_called_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
