# Generated by Django 4.2.3 on 2025-09-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_auth",
            "0009_user_last_withdraw_date_user_no_of_cash_deposited_and_more",
        ),
        ("game", "0004_game_winner"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGameParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times_played", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation",
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_participation",
                        to="custom_auth.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "game"], name="game_userga_user_id_b40a97_idx"
                    ),
                    models.Index(
                        fields=["game"], name="game_userga_game_id_73ebfe_idx"
                    ),
                ],
                "unique_together": {("user", "game")},
            },
        ),
    ]
