# Generated by Django 4.2.3 on 2025-10-14 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0005_usergameparticipation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=38, null=True
                    ),
                ),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                (
                    "money_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=38, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.BooleanField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AgentsAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("payment_method", models.SmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agents_account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomAuthAbstractuser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("date_joined", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "telegram_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "custom_auth_abstractuser",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DepositAccount",
            fields=[
                (
                    "deposit_payment_method",
                    models.CharField(
                        help_text="Payment method type (e.g., CBE, CBE_BIRR, TELEBIRR)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="The account number associated with the payment method",
                        max_length=255,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        help_text="Name of the account owner", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "deposit_account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=38, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("customer_chat_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "customer_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_method", models.SmallIntegerField(blank=True, null=True)),
                ("payment_status", models.SmallIntegerField(blank=True, null=True)),
                ("payment_type", models.SmallIntegerField(blank=True, null=True)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_source", models.SmallIntegerField(blank=True, null=True)),
                ("transactionsms", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "payment_request",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=38)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transfer_log",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="game",
            name="winner_cards",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="usergameparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_participation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CustomAuthUser",
            fields=[
                (
                    "abstractuser_ptr",
                    models.OneToOneField(
                        db_column="abstractuser_ptr_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="game.customauthabstractuser",
                    ),
                ),
                ("wallet", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bonus", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reserved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("no_of_games_played", models.IntegerField(blank=True, null=True)),
                ("no_of_cash_deposited", models.IntegerField(blank=True, null=True)),
                (
                    "total_withdraw_amount_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_withdraw_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_auth_user",
                "managed": False,
            },
        ),
    ]
