# Generated by Django 4.2.3 on 2025-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_agents_agentsaccount_customauthabstractuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="winner_cards",
        ),
        migrations.AddField(
            model_name="game",
            name="winner_card",
            field=models.IntegerField(default=0),
        ),
    ]
