# Generated by Django 4.2.22 on 2025-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_winner_cards_game_winner_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
