# Generated by Django 4.2.22 on 2026-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_winner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
